"""add_source_fps_and_log_path

Revision ID: ad462e64a750
Revises: fdccb634ba8d
Create Date: 2026-08-04 08:27:13.249044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad462e64a750'
down_revision: Union[str, Sequence[str], None] = 'fdccb634ba8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('source_fps', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'source_fps')
    # ### end Alembic commands ###
