"""Add processed_source_path

Revision ID: bd64ce9e0ae7
Revises: ad462e64a750
Create Date: 2026-08-05 09:54:41.856497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd64ce9e0ae7'
down_revision: Union[str, Sequence[str], None] = 'ad462e64a750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('processed_source_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'processed_source_path')
    # ### end Alembic commands ###
