"""Initial migration

Revision ID: f5c9fa007786
Revises: 
Create Date: 2026-08-03 15:23:07.969460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c9fa007786'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vod_uuid', sa.UUID(), nullable=False),
    sa.Column('enlace_id', sa.String(length=128), nullable=False),
    sa.Column('source_uri', sa.String(), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'PROBING', 'QUEUED', 'PROCESSING', 'VALIDATING', 'READY', 'FAILED', name='videostatus'), nullable=False),
    sa.Column('probe_metadata', sa.JSON(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('manifest_path', sa.String(), nullable=True),
    sa.Column('manifest_url', sa.String(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('source_width', sa.Integer(), nullable=True),
    sa.Column('source_height', sa.Integer(), nullable=True),
    sa.Column('video_codec', sa.String(), nullable=True),
    sa.Column('audio_codec', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enlace_id', name='uq_asset_enlace_id')
    )
    op.create_index(op.f('ix_assets_enlace_id'), 'assets', ['enlace_id'], unique=True)
    op.create_index(op.f('ix_assets_vod_uuid'), 'assets', ['vod_uuid'], unique=True)
    op.create_table('asset_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('TRANSITION', 'VALIDATION_FAILED', 'PROMOTED', 'ERROR', name='eventtype'), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('rq_job_id', sa.String(), nullable=True),
    sa.Column('worker_id', sa.String(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('heartbeat', sa.DateTime(), nullable=True),
    sa.Column('log_path', sa.String(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_rq_job_id'), 'jobs', ['rq_job_id'], unique=False)
    op.create_table('renditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('video_bitrate', sa.Integer(), nullable=True),
    sa.Column('audio_bitrate', sa.Integer(), nullable=True),
    sa.Column('playlist_path', sa.String(), nullable=False),
    sa.Column('segment_count', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('renditions')
    op.drop_index(op.f('ix_jobs_rq_job_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('asset_events')
    op.drop_index(op.f('ix_assets_vod_uuid'), table_name='assets')
    op.drop_index(op.f('ix_assets_enlace_id'), table_name='assets')
    op.drop_table('assets')
    
    # Drop enums that are not automatically dropped
    from sqlalchemy.dialects import postgresql
    videostatus = postgresql.ENUM('CREATED', 'PROBING', 'QUEUED', 'PROCESSING', 'VALIDATING', 'READY', 'FAILED', name='videostatus')
    videostatus.drop(op.get_bind())
    eventtype = postgresql.ENUM('TRANSITION', 'VALIDATION_FAILED', 'PROMOTED', 'ERROR', name='eventtype')
    eventtype.drop(op.get_bind())
    # ### end Alembic commands ###
