"""Add staged_source_path to Asset

Revision ID: fdccb634ba8d
Revises: fdd6eeed9e52
Create Date: 2026-08-03 21:07:33.384963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdccb634ba8d'
down_revision: Union[str, Sequence[str], None] = 'fdd6eeed9e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('staged_source_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'staged_source_path')
    # ### end Alembic commands ###
