"""Phase 2 fields and constraints

Revision ID: fdd6eeed9e52
Revises: 7e23839e86a2
Create Date: 2026-08-03 20:06:33.250267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdd6eeed9e52'
down_revision: Union[str, Sequence[str], None] = '7e23839e86a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('has_audio', sa.Boolean(), nullable=True))
    op.create_index('idx_unique_active_job', 'jobs', ['asset_id', 'type'], unique=True, postgresql_where=sa.text("status IN ('PENDING', 'PROCESSING')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_unique_active_job', table_name='jobs')
    op.drop_column('assets', 'has_audio')
    # ### end Alembic commands ###
